### ISSUE TITLE
S - Single responsibility

### ISSUE THREAD

**Issue by AlphaBeth** [dmittrey/Lab7#1]
Нужно внимательно следить за ответственностью каждого класса.

DBWorker не должен формировать какие-то сообщения для клиента (об ошибке, например) - он должен просто отдавать какой-то объект с результатом исполнения команды и статусом/бросать исключение.

Сервер не должен форматировать сообщения (добавлять цвета и пр.) - это задача клиента.

**Comment by dmittrey** [comment]
Отправляю коды отработки команды и полезные данные если все прошло удачно
https://github.com/dmittrey/Lab7/blob/e4531bbeb3bc665d30c61e7c480a479a08b5bc94/Legacy/src/main/java/utility/TypeOfAnswer.java#L5-L16

Затем на клиенте анимирую с помощью объекта класса
https://github.com/dmittrey/Lab7/blob/main/Client/src/main/java/utility/Animator.java
