### ISSUE TITLE
Проверять логин и пароль перед каждой командой

### ISSUE THREAD

**Issue by AlphaBeth** [dmittrey/Lab7#2]
Сейчас сервер верит клиенту - если он прислал логин, то пароль проверили когда-то раньше. Это правда лишь для вашего клиента, но в целом - нет, так как можно поменять клиент таким образом, чтобы он не проверял пароль.

**Comment by dmittrey** [comment]
https://github.com/dmittrey/Lab7/blob/e4531bbeb3bc665d30c61e7c480a479a08b5bc94/Server/src/main/java/utility/Invoker.java#L29-L36
