### ISSUE TITLE
Непотокобезопасное хранение истории команд

### ISSUE THREAD

**Issue by AlphaBeth** [dmittrey/Lab7#3]
Нужно либо добавить синхронизацию в добавление истории, либо заменить все коллекции для истории на потокобезопасные аналоги (не только мапу, но и хранящийся в ней deque).

**Comment by dmittrey** [comment]
https://github.com/dmittrey/Lab7/blob/aad8298cf35a2adfc5084947ce1542069d0af057/Server/src/main/java/utility/Receiver.java#L23-L30

**Comment by dmittrey** [comment]
https://github.com/dmittrey/Lab7/blob/aad8298cf35a2adfc5084947ce1542069d0af057/Server/src/main/java/utility/Receiver.java#L126-L135

**Comment by AlphaBeth** [comment]
putIfAbsent/computeIfAbsent
